""" Error Codes
    Author: vipulasrilanka@yahoo.com 
    (c) 2024 """

ERROR_SUCCESS = 0
ERROR_FILE_NOT_FOUND = 1
ERROR_FILE_OPEN_ERROR = 2
ERROR_TEMP_FILE_DELETE = 3
ERROR_FILE_ENCRYPTED = 4
ERROR_ITEM_NOT_FOUND = 5
ERROR_NULL_STRING = None
ERROR_GENERAL_FAILIURE = 8
ERROR_UNKNOWN = 9