PDF_FIRST_PAGE = 0

def getPdfPage(pageNumber):
    return pageNumber - 1

PDF_DEFAULT_FONT = "Helvetica"
PDF_DEFAULT_FONT_SIZE = 12
PDF_DEFAULT_LINE_SPACE_FACTOR = 1.2
PDF_DEFAULT_LINE_SPACE = PDF_DEFAULT_FONT_SIZE * PDF_DEFAULT_LINE_SPACE_FACTOR
MM_PER_INCH = 25.4
PDF_DPI = 72
PDF_DPMM = PDF_DPI / MM_PER_INCH