name: Build and Package Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install openpyxl
          pip install git+https://github.com/nolze/msoffcrypto-tool.git
          pip install num2words
          pip install PyPDF2          
          pip install reportlab
          
      # Step 4: Build the project into an executable
      - name: Build executable
        run: |
          pyinstaller --onefile src/main.py
          ls dist  # Show the output executable directory

      # Step 5: Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: python-app-executable
          path: dist/main.exe
